spring.application.name=spring-admin-client
server.port=5021
spring.profiles.active=dev


#Spring Boot Admin Settings
spring.boot.admin.client.url=http://localhost:8086
spring.boot.admin.client.instance.name=AdminClient
spring.boot.admin.client.instance.service-url=http://localhost:5021
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=P@ssword1


#Actuator Endpoint Settings
# Metric de?erleri için
management.endpoints.web.base-path=/actuator
#Local Servis oldu?undan Spring Boot Admin Her?eyi görüntülesin
management.endpoints.web.exposure.include=*
